on: [ "push", "pull_request" ]

name: "Run tests"

jobs:
  linux:
    name: "Run tests Linux"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04 ]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache-soft
        with:
          path: soft
          key: ${{ matrix.os }}-${{ hashFiles('Makesurefile') }}

      - name: "run tests"
        run: |
          ./makesure tested_awks
  mac:
    name: "Run tests Mac"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-13, macos-14, macos-15 ]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache-soft
        with:
          path: soft
          key: ${{ matrix.os }}-${{ hashFiles('Makesurefile') }}

      - name: "run tests"
        run: |
          CompareToBash=0 ./makesure
  win:
    name: "Run tests Win"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2022, windows-2025 ]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache-soft
        with:
          path: soft
          key: ${{ matrix.os }}-${{ hashFiles('Makesurefile') }}

      - name: "run tests"
        run: |
          & bash -e -c ./makesure
