on: [ "push", "pull_request" ]

name: "Run tests"

jobs:
  linux:
    name: "Run tests Linux"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, ubuntu-22.04 ]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache-soft
        with:
          path: soft
          key: ${{ runner.os }}-soft-3

      - name: "run tests"
        run: |
          ./makesure tested_awks
  mac:
    name: "Run tests Mac"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-11, macos-12, macos-13 ]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache-soft
        with:
          path: soft
          key: ${{ runner.os }}-soft-2

      - name: "run tests"
        run: |
          ./makesure
  win:
    name: "Run tests Win"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2019, windows-2022 ]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache-soft
        with:
          path: soft
          key: ${{ runner.os }}-soft-3

      - name: "run tests"
        run: |
          & bash -e -c ./makesure
